/*
 * File: app/view/MyForm2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArtExchange.view.MyForm2', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.form.field.File',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    height: 350,
    itemId: 'myform2',
    width: 591,
    bodyPadding: 10,
    title: 'Add Item',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Name',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Category',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Description'
                },
                {
                    xtype: 'datefield',
                    anchor: '100%',
                    fieldLabel: 'Created'
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Tags'
                },
                {
                    xtype: 'filefield',
                    anchor: '100%',
                    fieldLabel: 'Upload File'
                },
                {
                    xtype: 'radiogroup',
                    fieldLabel: 'Type',
                    allowBlank: false,
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Item'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Service'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    formBind: true,
                    text: 'MyButton'
                }
            ]
        });

        me.callParent(arguments);
    }

});