/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ArtExchange.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Ext.panel.Panel',
        'Ext.tab.Tab'
    ],

    height: 250,
    width: 400,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 214,
                    width: 400,
                    title: 'Items'
                },
                {
                    xtype: 'panel',
                    title: 'Services'
                },
                {
                    xtype: 'panel',
                    title: 'Common/Shared Items'
                }
            ]
        });

        me.callParent(arguments);
    }

});